In [1]:
1 + 1

2

In [2]:
3 *4

12

In [2]:
import numpy as np

In [11]:
a = np.array([0,1,2,3,4])

In [9]:
a[0]

0

In [10]:
a[4]

4

In [12]:
type(a)

numpy.ndarray

In [13]:
a.size

5

In [14]:
a.ndim

1

In [15]:
a.shape

(5,)

In [16]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [17]:
type(b)

numpy.ndarray

In [24]:
b.dtype

dtype('float64')

In [21]:
c = np.array([20,1,2,3,4])
c

array([20,  1,  2,  3,  4])

In [22]:
c[0] = 100

In [23]:
c

array([100,   1,   2,   3,   4])

In [30]:
d = c[1:4]
d

array([1, 2, 3])

In [31]:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [34]:
u = [1,0]
v = [0,1]
z = []
for n,m in zip(u,v):
    z.append(n+m)
    
z

[1, 1]

In [44]:
u = np.array([1,0])
v = np.array([0,1])
z = u + v
z

array([1, 1])

# Substraction

In [38]:
u = [1,0]
v = [0,1]
z = []
for n,m in zip(u,v):
    z.append(n-m)
    
z

[1, -1]

In [39]:
u = np.array([1,0])
v = np.array([0,1])
z = u - v
z

array([ 1, -1])

In [47]:
y = np.array([1,2])
z = 2*y
z

array([2, 4])

In [48]:
y = [1,2]
z = []
for n in y:
    z.append(2*n)
z

[2, 4]

## Product of two Numpy array

In [3]:
u = np.array([1,2])
v = np.array([3,2])
z = u * v
z

array([3, 4])

In [4]:
u= [1,2]
v= [3,2]
z = []
for m,n in zip(u,v):
    z.append(m*n)
z

[3, 4]

## dot Product

In [6]:
u = np.array([1,2])
v = np.array([3,1])
z = np.dot(u,v)
z

5

## Adding constant to an Numpy Array

In [7]:
u = np.array([1,2,3,-1])
z = u +1
z

array([2, 3, 4, 0])

## Universal Function

In [14]:
#Mean Function
a = np.array([-1,1,-1,1])
mean_a = a.mean()
mean_a

0.0

In [16]:
#Max Function
b = np.array([1, -2,3,4,5])
max_b = b.max()
max_b

5